#Q1

#**A:**
impliment a hopfield network for below patterns:
<br>
X1 = [-1, -1, 1, -1, 1, -1, -1, 1]
<br>
X2 = [-1, -1, -1, -1, -1, 1, -1, -1]
<br>
X3 = [-1, 1, 1, -1, -1, 1, -1, 1]

then show is the network stable for top patterns?

In [ ]:
import numpy as np
import math

In [ ]:
x1 = np.array([-1, -1, 1, -1, 1, -1, -1, 1])
x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1])
x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1])
P = np.array([x1, x2, x3])

In [ ]:
class Hopfield:
    def __init__(self, N):
        self.N = N
        self.P = 0
        self.W = np.zeros((N, N), dtype=np.int32)

In [ ]:
def training(Hopfield, P):
      for Xi in P:
          sta = np.vstack(Xi)
          Hopfield.W += np.dot(sta, sta.T)
      np.fill_diagonal(Hopfield.W, 0.0)
      return Hopfield.W

In [ ]:
def prediction(Hopfield, start):
      epochs = 10
      is_stable = False
      result = [(start, math.inf)]
      for i in range(epochs):
          start = np.sign(np.dot(start, Hopfield.W))
          h = np.count_nonzero(np.equal(input, start))
          d = Hopfield.P - h
          result.append((start,d))

          if np.array_equal(result[-1][0], result[-2][0]):
              if i == 0:
                  is_stable=True
              return start, is_stable

      return min(result, key = lambda t: t[1])[0], is_stable

In [ ]:
HN = Hopfield(8)
W = training(HN, P)
print("Weight : ")
print(W)

Weight : 
[[ 0  1 -1  3  1 -1  3 -1]
 [ 1  0  1  1 -1  1  1  1]
 [-1  1  0 -1  1 -1 -1  3]
 [ 3  1 -1  0  1 -1  3 -1]
 [ 1 -1  1  1  0 -3  1  1]
 [-1  1 -1 -1 -3  0 -1 -1]
 [ 3  1 -1  3  1 -1  0 -1]
 [-1  1  3 -1  1 -1 -1  0]]


In [ ]:
#x1 = np.array([-1, -1, 1, -1, 1, -1, -1, 1])
out1, res1 = prediction(HN, x1)
print(out1, res1)
# x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1])
out2, res2 = prediction(HN, x2)
print(out2, res2)
# x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1])
out3, res3 = prediction(HN, x3)
print(out3, res3)

[-1 -1  1 -1  1 -1 -1  1] True
[-1 -1 -1 -1 -1  1 -1 -1] True
[-1  1  1 -1 -1  1 -1  1] True


#**‌B:**
show is the network stable for noisy patterns?
<br>
X1n = [1, -1, 1, -1, 1, -1, -1, 1]
<br>
X2n = [1, 1, -1, -1, -1, 1, -1, -1]
<br>
X3n = [1, 1, 1, -1, 1, 1, -1, 1]

In [ ]:
X1n = [1, -1, 1, -1, 1, -1, -1, 1]
out1, res1 = prediction(HN, X1n)
print(out1)
X2n = [1, 1, -1, -1, -1, 1, -1, -1]
out2, res2 = prediction(HN, X2n)
print(out2)
X3n = [1, 1, 1, -1, 1, 1, -1, 1]
out3, res3 = prediction(HN, X3n)
print(out3)

[-1 -1  1 -1  1 -1 -1  1]
[-1 -1 -1  1 -1  1  1 -1]
[-1  1  1 -1 -1 -1 -1  1]


# **C:**
Find Stable patterns

In [ ]:
results = []
pattern_size = 8
for i in range(2**8):
    j = bin(i)[2:].zfill(pattern_size)
    patern_i = [2*int(j[k])-1 for k in range(pattern_size)]
    out,res = prediction(HN, patern_i)
    if res == True:
        print(out)


[-1 -1 -1 -1 -1  1 -1 -1]
[-1 -1  1 -1  1 -1 -1  1]
[-1  1  1 -1 -1  1 -1  1]
[ 1 -1 -1  1  1 -1  1 -1]
[ 1  1 -1  1 -1  1  1 -1]
[ 1  1  1  1  1 -1  1  1]
